name: Verify changes

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: '14.x'

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm i -g npm@7 # Force npm@7 to support workspaces

      - run: npm ci
      - run: npm run lint

  analyze-lit:
    name: Analyze Lit

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm i -g npm@7 # Force npm@7 to support workspaces

      - run: npm ci
      - run: npm run analyze-lit

  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm i -g npm@7 # Force npm@7 to support workspaces

      - run: npm ci
      - run: npx playwright install-deps
      - run: npm test
